---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scripthpascaler-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - '*/scale'
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - busybox.org
  resources:
  - scripthpascalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - busybox.org
  resources:
  - scripthpascalers/finalizers
  verbs:
  - update
- apiGroups:
  - busybox.org
  resources:
  - scripthpascalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - update
  - watch
