apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: supersetscaler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: supersetscaler-role
subjects:
- kind: ServiceAccount
  name: supersetscaler
  namespace: kube-system
